version: '3.8'

services:
  postgres:
    image: postgres
    container_name: rbs-postgres
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  consul:
    image: hashicorp/consul
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      
  leveldb-server:
    image: cardial/leveldbreader:latest
    container_name: leveldb
    ports:
      - "2012:2012"
    volumes:
      - leveldb:/opt/app/db
    environment:
      leveldb_path: /opt/app/db
      leveldb_host: 0.0.0.0
      leveldb_port: 2012
      leveldb_keyEncoding: utf8
      leveldb_valueEncoding: json
      leveldb_defaultTTL: 0
      leveldb_checkFrequency: 50

volumes:
  postgres_data:
  leveldb:
